/**
 * Generate `sw.js` — the service worker's precache list and its version.
 *
 * Run this whenever files are added, removed or changed:
 *
 *     node tools/build-sw.mjs
 *
 * and commit the result. It is deliberately *not* wired into the deploy: the
 * website ships with no build step at all (Cloudflare Pages serves the repo
 * root directly), and the whole point of that is having nothing that can fail
 * between a push and a working site.
 *
 * The version is a hash of every file's contents, so any change to any asset
 * produces a new cache name, the old cache is deleted on activate, and nobody
 * is left running a half-old copy. If you forget to re-run this, the worst case
 * is that returning visitors keep the previous version until they load online
 * again — `index.html` is fetched network-first precisely so that self-corrects.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** Everything the app needs to run with no network. */
const INCLUDE_DIRS = ['assets/fonts', 'assets/textures', 'src', 'styles'];
const INCLUDE_FILES = [
  'index.html',
  'manifest.webmanifest',
  'favicon.svg',
  'icon-192.png',
  'icon-512.png',
  'apple-touch-icon.png',
];

function walk(dir, out = []) {
  for (const name of readdirSync(join(ROOT, dir))) {
    const rel = `${dir}/${name}`;
    if (statSync(join(ROOT, rel)).isDirectory()) walk(rel, out);
    else out.push(rel);
  }
  return out;
}

const files = [
  ...INCLUDE_FILES,
  ...INCLUDE_DIRS.flatMap((d) => walk(d)),
].map((f) => f.split(sep).join('/')).sort();

// Version from the contents of every file, not from a timestamp — rebuilding
// without changing anything should not invalidate anyone's cache.
const hash = createHash('sha256');
for (const f of files) {
  hash.update(f);
  hash.update(readFileSync(join(ROOT, f)));
}
const VERSION = hash.digest('hex').slice(0, 12);

const sw = `/**
 * Service worker — GENERATED by tools/build-sw.mjs. Do not edit by hand.
 *
 * Ritual makes no network requests once it has loaded, so it is a natural fit
 * for working offline: precache everything, then serve from the cache.
 *
 * The one thing to get right is staleness. \`index.html\` is fetched
 * network-first, so a deploy is picked up on the next online load and a stale
 * cache can always correct itself. Everything else is cache-first, keyed to a
 * version derived from the contents of every file — so a changed asset means a
 * new cache name, and the old one is deleted on activate.
 */

const VERSION = '${VERSION}';
const CACHE = \`ritual-\${VERSION}\`;

const PRECACHE = ${JSON.stringify(files.map((f) => './' + f), null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      // Individually, so one failed asset cannot fail the whole install.
      .then((cache) => Promise.all(
        PRECACHE.map((url) => cache.add(url).catch(() => {}))
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('ritual-') && k !== CACHE)
            .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // The document is network-first: it is the only file that can tell the
  // browser about a new version, so it must never be pinned.
  const isDocument = req.mode === 'navigate' ||
    (req.headers.get('accept') || '').includes('text/html');

  if (isDocument) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(req).then((r) => r || caches.match('./index.html')))
    );
    return;
  }

  // Everything else is content the version already accounts for.
  event.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res && res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
      }
      return res;
    }))
  );
});
`;

writeFileSync(join(ROOT, 'sw.js'), sw, 'utf8');
console.log(`sw.js written — version ${VERSION}, ${files.length} files precached`);
